export enum LogEvent {
  SYNC_STARTED = 'SYNC_STARTED',
  SYNC_COMPLETED = 'SYNC_COMPLETED',
  SYNC_PROCESSING = 'SYNC_PROCESSING',
  SYNC_PROGRESS = 'SYNC_PROGRESS',
  SYNC_STATS = 'SYNC_STATS',

  REQUEST_INTERCEPTED = 'REQUEST_INTERCEPTED',
  REQUEST_QUEUED = 'REQUEST_QUEUED',
  REQUEST_DEQUEUED = 'REQUEST_DEQUEUED',
  REQUEST_SYNCED = 'REQUEST_SYNCED',
  REQUEST_SYNC_FAILED = 'REQUEST_SYNC_FAILED',
  REQUEST_FAILED_PERMANENTLY = 'REQUEST_FAILED_PERMANENTLY',
  REQUEST_QUEUE_FAILED = 'REQUEST_QUEUE_FAILED',

  RETRY_SCHEDULED = 'RETRY_SCHEDULED',
  RETRY_STARTED = 'RETRY_STARTED',

  NETWORK_ONLINE = 'NETWORK_ONLINE',
  NETWORK_OFFLINE = 'NETWORK_OFFLINE',

  QUEUE_EMPTY = 'QUEUE_EMPTY',
  QUEUE_CLEARED = 'QUEUE_CLEARED',
}
